services:
  bot:
    image: ghcr.io/unreal-engine-fr/bidibip:latest
    restart: unless-stopped
    volumes:
      - ./Saved:/opt/bidibip/Saved
      - ./plugins:/opt/bidibip/plugins
      - ./.env:/opt/bidibip/.env
